version: '3.3'

services:
  data-base-server:
    container_name: data-base-server
    image: mysql:8.0.20
    command: mysqld --lower_case_table_names=1 --skip-ssl
      --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
      --sql_mode="" --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'OCMSoliServer'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'other'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'M163lr9u6j2v'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-network
  solicitudes:
    container_name: solicitudes
    build:
      context: ./
    ports:
      - '80:8081'
    environment:
      - DATABASE_URL=mysql://root:M163lr9u6j2v@data-base-server:33060/OCMSoliServer # TODO Cambiar despues el usuario y contraseña
      - NODE_ENV=prod
      - HOSTNAME=data-base-server
      - SSL=true
      - NODE_SERVER_PORT=8081
    depends_on:
      - data-base-server
    links:
      - data-base-server
    networks:
      - my-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - data-base-server
    environment:
      PMA_HOST: data-base-server
      PMA_PORT: 33060
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
    networks:
      - my-network
# Names our volume
volumes:
  my-db: null
networks:
  my-network: null
